WIFI_SSID = "YOUR_2_4_GHZ_HOTSPOT_NAME"
WIFI_PASSWORD = "YOUR_HOTSPOT_PASSWORD"

DEVICE_ID = "ESP32-01"
DEVICE_SECRET = "USE_THE_SERVER_ESP32_DEMO_SECRET_VALUE"

API_BASE_URL = "https://hanwoo.koreacentral.cloudapp.azure.com"
