WIFI_SSID = "YOUR_2_4_GHZ_HOTSPOT_NAME"
WIFI_PASSWORD = "YOUR_HOTSPOT_PASSWORD"

DEVICE_ID = "ESP32-01"
IOT_HUB_HOSTNAME = "cow-hub.azure-devices.net"
IOT_HUB_DEVICE_KEY = "PASTE_ESP32_01_PRIMARY_KEY_HERE"
